## indexing in array


In [1]:
import numpy as np
arr = np.array([10,20,30,40,50])
arr[0]

np.int64(10)

In [2]:
arr[-1]

np.int64(50)

In [3]:
arr[1]

np.int64(20)

## 2D array

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,1])

2


In [5]:
print(arr[1,2])

6


## indexing in 1D array

In [6]:
a = np.array([10,20,30,40])
# first element
print("First lement:" ,a[0])
# last element           
print("Last Elemet:" ,a[-1])



First lement: 10
Last Elemet: 40


In [7]:
# slicing in  1D Array
a = np.array([10,20,30,40,50])
print("extract 20 to 40:" , a[1:4])
print("Extract form starting to 30:" , a[:3])
print("Extract from 40 to end: " ,a[3:])
print("extract by step 2:" ,a[::2])
print("Reverse array:",a[::-1])

extract 20 to 40: [20 30 40]
Extract form starting to 30: [10 20 30]
Extract from 40 to end:  [40 50]
extract by step 2: [10 30 50]
Reverse array: [50 40 30 20 10]


In [8]:
# indexing  in 2D
a = np.array([[1,2,3], [4,5,6]])
print("Extract 2 element:" ,a[0,1])
print("Extract 6:",a  [1,2])

# slicing in 2D
print("second column:",a[:,1])
print("first row:" ,a[0,:])
print("extract 2,3 and 5,6:",a[:,1:])      
      

Extract 2 element: 2
Extract 6: 6
second column: [2 5]
first row: [1 2 3]
extract 2,3 and 5,6: [[2 3]
 [5 6]]


In [9]:
# fancy indexing
a = np.array([10,20,30,40,50])
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [10]:
# fancy indexing
a = np.array([10,20,30,40,50,])
print("Extract only 10 and 30:",a[[0,2]])
      

Extract only 10 and 30: [10 30]


In [11]:
# boolean indexing
print(a[a>20])

[30 40 50]


In [12]:
# modify vaue using indexing
a[1] = 100
print(a)

[ 10 100  30  40  50]


In [13]:
marks = np.array([45,67,89,34,90])
# student who passed
print(marks[marks>=40])

# Top scores
print(marks[marks>80])

[45 67 89 90]
[89 90]


In [14]:
# airthmaic operator

a  = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a -b)


[5 7 9]
[-3 -3 -3]


In [15]:
# broadcasting: automatic expansion of arrsy
a = np.array([1,2,3])
print(a + 10)


[11 12 13]


In [16]:
a =np.array([[1,2,3],
            [4,5,6]])
b = np.array([10,20,30])
print(a+b)

[[11 22 33]
 [14 25 36]]


In [17]:
# universal fiunctions
a = np.array([1,4,9])
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))

[1. 2. 3.]
[0.         1.38629436 2.19722458]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
[ 0.84147098 -0.7568025   0.41211849]


In [18]:
# agrgregation function
a = np.array([10,20,30])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))

60
20.0
10
30


In [19]:
a = np.array([[1,2,3],
              [4,5,6]])
# row wise
print(np.sum(a,axis=1))
# column wise
print(np.sum(a,axis=0))

[ 6 15]
[5 7 9]


In [20]:
# resahpe
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [21]:
b = a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [22]:
# convert multi dimensional array into 1 D array
# floaten() = copy
a = np.array([[1,2],[3,4]])
b= a.flatten()
print(b)
b[0]= 100
print(b)
print(a)

[1 2 3 4]
[100   2   3   4]
[[1 2]
 [3 4]]


In [23]:
# ravel() = view
c = a.ravel()
print(c)
c[0]=200
print(c)
print(a)

[1 2 3 4]
[200   2   3   4]
[[200   2]
 [  3   4]]


In [24]:
# Transpose
a =np.array([[1,2,3], [4,5,6]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
a = np.arange(6)
a.resize(4,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 0]])

In [26]:
# joining and spliting array
import numpy as np
# joining
a = np.array([1,2])
b = np.array([3,4])
print(np.concatenate((a,b)))

[1 2 3 4]


In [27]:
# concatenate() with 2D aray
# column -wise
a = np.array([[1,2],
              [3,4]])
b = np.array([[5],
              [4]])
print(np.concatenate((a,b),axis=1))

[[1 2 5]
 [3 4 4]]


In [28]:
#vestack
a= np.array([1,2,3])
b= np.array([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [29]:
#  hstack

a = np.array([1,2,3])
b= np.array([4,5,6])
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [30]:
# column_Stack
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.column_stack((a,b)))

[[1 4]
 [2 5]
 [3 6]]


In [31]:
# destack()
a = np.array([[1,2]])
b = np.array([[3,4]])
print(np.dstack((a,b)))


[[[1 3]
  [2 4]]]


In [32]:
# splitting array
# 1 . split()
a = np.array([1,2,3,4,5,6])
print(np.split(a,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [33]:
# 2 array_split()
a = np.array([1,2,3,4,5])
print(np.array_split(a,3))

[array([1, 2]), array([3, 4]), array([5])]


In [34]:
# spliting in 2D arraty
# row-wise
a= np.array([[1,2],
             [3,4],
             [5,6]])
print(np.array_split(a,2,axis = 0))

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]


In [35]:
a = np.array([[1,2],
              [3,4],
              [5,6]])
print(np.array_split(a,2,axis = 1))

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [36]:
# hplit
a = np.array([[1,2],
              [3,4]])
print(np.hsplit(a,2))

[array([[1],
       [3]]), array([[2],
       [4]])]


In [37]:
print(np.vsplit(a,2))

[array([[1, 2]]), array([[3, 4]])]


In [38]:
# copy vs view
# copy
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print("original array:" , a)
print("copied array:",b)
print("original array:", a)

original array: [1 2 3]
copied array: [100   2   3]
original array: [1 2 3]


In [39]:
# view 
import numpy as np
a = np.array([10,20,30])
print("original array:" , a)
b = a.view()
b[0]= 100
print("copied array:", b)
print("original array:", a)

original array: [10 20 30]
copied array: [100  20  30]
original array: [100  20  30]


In [40]:
# iteration:

# mean accessing elements of an array one by one

In [41]:
# basic iteration (1D array)
a = np.array([10,20,30])
for i in a:
    print(i*3)

30
60
90


In [42]:
# iteraation 2D array
a = np.array([[1,2],
              [3,4]])
for row in a:
    print(row)

[1 2]
[3 4]


In [43]:
# element wise iteration (nested loop)
for row in a:
    for element in row:
        print(element)

1
2
3
4


In [44]:
# np.nditer()- used for efficient iteration in multi demension array

a = np.array([[1,2],
              [3,4]])
for x in np.nditer(a):
    print(x)

1
2
3
4


In [45]:
# iteration with index
a = np.array([[1,2],
              [3,4]])
for index,value in np.ndenumerate(a):
    print(index,value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [46]:
# np.sort()- return a sorted array (original array remains unchanged)
a = np.array([3,1,2])
b = np.sort(a)
b

array([1, 2, 3])

In [51]:
a = np.array([[3,1],
              [4,2]])
print(np.sort(a))

[[1 3]
 [2 4]]


In [52]:
print(np.sort(a,axis = 0))

[[3 1]
 [4 2]]


In [54]:
#  np.argsort()
import numpy as np
a = np.array([30, 10, 20]) #30 - 0 1 - 1 20 -2
print(a)
print(np.sort(a))
print(np.argsort(a))

[30 10 20]
[10 20 30]
[1 2 0]


In [55]:
# np.where()- returns indices where condition is true
a = np.array([10,20,30,40])
print(np.where(a>20))


(array([2, 3]),)


In [56]:
# np.searchsorted() - return indices whwre element should be insered to maintain order
print(np.searchsorted(a,25))

2


In [57]:
# np.argmax()- it returns index of max value
print(np.argmax(a))

3


In [58]:
print(np.argmin(a))

0


In [59]:
# dot product
a= np.array([1,2])
b = np.array([3,4])
print(np.dot(a,b))

11


In [63]:
# matrix multiplication
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(a @ b)

[[19 22]
 [43 50]]


In [65]:
a = np.array([[10 ,20], [30,40]])
b = (np.linalg.inv(a))
b

array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])